#!/bin/bash

# Commit message must be in correct format
# https://www.conventionalcommits.org/

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# get number of commit parents
commit_number_of_parents=$(git cat-file -p $(git rev-parse HEAD) | grep parent | wc -l)

if [[ $commit_number_of_parents < 2 ]]; then
  # commit headline must be in the correct format
  commit_msg_file=$(git rev-parse --git-dir)/COMMIT_EDITMSG

  # Read the commit message from the COMMIT_EDITMSG file
  commit_msg=$(cat "$commit_msg_file")

  # Regular expression pattern for conventional commit format
  pattern="^(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|wip|release|BREAKING CHANGE)(\(.+\))?: .{1,}"

  # Check if the commit message matches the pattern
  if [[ ! $commit_msg =~ $pattern ]]; then
    printf "${RED}Aborting. ${YELLOW}Your commit message is invalid.${NC}

Syntax:
${YELLOW}<type>${NC}(${YELLOW}<scope>${NC}): ${YELLOW}<subject>${NC}

    ${YELLOW}<type>${NC} can be one of
    build chore ci docs feat fix perf refactor revert style test

    ${YELLOW}<scope>${NC} is optional

    ${YELLOW}<subject>${NC} there must be a description of the change

    Find more on this topic here:
    - ${GREEN}https://www.conventionalcommits.org/${NC}
"
    exit 1
  fi
fi
